import { createServer as createHttpServer } from 'node:http';
import { once } from 'node:events';
import { createMcpHandler, McpServer } from '@modelcontextprotocol/server';
import { toNodeHandler } from '@modelcontextprotocol/node';
import { registerTools } from './tools.mjs';
import { createConnectorRuntime, createRuntimeStub } from './runtime.mjs';
export const SERVICE='nova-vix-chatgpt'; export const VERSION='0.1.0'; const NOAUTH=[{type:'noauth'}];
function installSecurityProjection(protocol){const original=protocol._getRequestHandler?.('tools/list');if(!original)throw new Error('MCP tools/list handler is unavailable for OpenAI security projection');protocol.removeRequestHandler('tools/list');protocol.setRequestHandler('tools/list',async(req,ctx)=>{const out=await original(req,ctx);return {...out,tools:out.tools.map(t=>({...t,securitySchemes:t.securitySchemes??t._meta?.securitySchemes??NOAUTH}))};});}
export function createMcpServer(runtime){const server=new McpServer({name:SERVICE,version:VERSION},{instructions:'Start stock Vix with vix_open. Use vix_exchange for native Vix events and raw model inference checkpoints. This ChatGPT must answer every request_id itself. Vix remains stock; no provider inference fallback is allowed.'});registerTools(server,runtime);installSecurityProjection(server.server);return server;}
function json(res,status,body){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(body));}
function loopbackHost(v){if(typeof v!=='string')return false;const h=v.trim().toLowerCase();return /^127\.0\.0\.1(?::\d+)?$/.test(h)||/^localhost(?::\d+)?$/.test(h)||/^\[::1\](?::\d+)?$/.test(h);}
export function createApp({runtime=createRuntimeStub()}={}){const mcpHandler=createMcpHandler(async()=>createMcpServer(runtime),{legacy:'stateless',responseMode:'auto',onerror:e=>console.error('[mcp]',e?.message||String(e))});const handleMcp=toNodeHandler(mcpHandler);const httpServer=createHttpServer(async(req,res)=>{try{const url=new URL(req.url??'/','http://'+(req.headers.host??'127.0.0.1'));if(url.pathname==='/healthz'&&req.method==='GET'){const h=await runtime.health().catch(error=>({ok:false,modelCalls:0,error:error?.message||String(error)}));json(res,200,{...h,runtimeReady:h.ok===true,service:SERVICE,version:VERSION,transport:'streamable-http',buildSha:process.env.NOVA_BUILD_SHA||null});return;}if(url.pathname==='/readyz'&&req.method==='GET'){const h=await runtime.health().catch(error=>({ok:false,modelCalls:0,error:error?.message||String(error)}));const ready=h.ok===true&&h.modelCalls===0;json(res,ready?200:503,{...h,ready,service:SERVICE,version:VERSION,transport:'streamable-http',buildSha:process.env.NOVA_BUILD_SHA||null});return;}if(url.pathname!=='/mcp'){json(res,404,{error:'not_found'});return;}if(!loopbackHost(req.headers.host)){json(res,403,{error:'invalid_host'});return;}await handleMcp(req,res);}catch(error){console.error('[mcp]',error?.message||String(error));if(!res.headersSent)json(res,500,{jsonrpc:'2.0',error:{code:-32603,message:'Internal server error'},id:null});else if(!res.writableEnded)res.end();}});let closed=false;async function close(){if(closed)return;closed=true;await mcpHandler.close();await runtime.close?.().catch(()=>{});if(httpServer.listening)await new Promise((r,j)=>httpServer.close(e=>e?j(e):r()));}return {runtime,httpServer,close};}
export async function listen({port=Number(process.env.PORT||18816),host=process.env.HOST||'127.0.0.1',runtime=createRuntimeStub()}={}){const app=createApp({runtime});app.httpServer.listen(port,host);await once(app.httpServer,'listening');return app;}
async function main(){if(process.env.NOVA_VIX_TEST_MODE==='1')return listen({runtime:createRuntimeStub()});return listen({runtime:await createConnectorRuntime()});}
if(import.meta.url===`file://${process.argv[1]}`){main().then(app=>{const shutdown=async()=>{await app.close();process.exit(0);};process.once('SIGTERM',shutdown);process.once('SIGINT',shutdown);}).catch(error=>{console.error(error?.message||String(error));process.exitCode=1;});}
