import { z } from 'zod/v4';
const SECURITY=[{type:'noauth'}]; const META={securitySchemes:SECURITY}; const uuid=z.string().uuid(); const openRecord=z.record(z.string(),z.unknown());
function toolResult(structuredContent,text='Structured result available.'){return {structuredContent,content:[{type:'text',text}]};}
function descriptor(c){return {...c,securitySchemes:SECURITY,_meta:{...c._meta,...META}};}
export function registerTools(server,runtime){
 server.registerTool('vix_open',descriptor({title:'Open or resume stock Vix',description:'Start stock Vix with ChatGPT-only inference. Supply resume_id to rebind an existing live Goal without duplicating effects; the reference is persisted durably.',inputSchema:z.object({cwd:z.string().min(1).optional().describe('Project working directory for a new Goal.'),prompt:z.string().min(1).optional().describe('Instruction for a new Goal.'),workflow:z.string().min(1).optional().describe('Optional native Vix workflow name passed unchanged to -w.'),resume_id:uuid.optional().describe('Stable connector Goal reference returned by vix_open.')} ).strict().refine(a => Boolean(a.resume_id) || (a.cwd && a.prompt), { message:'cwd and prompt are required for a new Goal, or provide resume_id' }),outputSchema:z.object({connection_id:uuid,resume_id:uuid,native_thread_id:z.string().nullable(),vix_version:z.string(),modelCalls:z.literal(0)}).strict(),annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true,idempotentHint:false},_meta:{'openai/toolInvocation/invoking':'Starting or resuming Vix','openai/toolInvocation/invoked':'Vix Goal ready'}}),async a=>toolResult(await runtime.open(a),'Stock Vix started or resumed with ChatGPT-only inference routing.'));
 server.registerTool('vix_exchange',descriptor({title:'Exchange Vix checkpoints',description:'Return only new Vix events. A still-pending inference checkpoint is replayed in full until accepted; consumed history is not re-emitted. ChatGPT must answer every request_id itself.',inputSchema:z.object({connection_id:uuid,inference_responses:z.array(z.object({request_id:uuid,response:openRecord.describe('Assistant response. A normalized {content:[{type:text,text}|{type:tool_use,id,name,input}], stop_reason} form works across all supported Vix wires.')} ).strict()).default([]),wait_ms:z.number().int().min(0).max(30000).default(1000)}).strict(),outputSchema:z.object({connection_id:uuid,resume_id:uuid,events:z.array(openRecord),inference_requests:z.array(z.object({request_id:uuid,protocol:z.string(),wire_format:z.string(),request:openRecord,headers:openRecord}).strict()),closed:z.boolean(),exit_code:z.number().int().nullable(),mission_control_url:z.string().nullable(),modelCalls:z.literal(0),error:z.string().nullable()}).strict(),annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true,idempotentHint:false},_meta:{'openai/toolInvocation/invoking':'Exchanging Vix checkpoints','openai/toolInvocation/invoked':'Vix checkpoints exchanged'}}),async a=>toolResult(await runtime.exchange(a)));
 server.registerTool('vix_read_inference_context',descriptor({title:'Read Vix inference context',description:'Read an exact JSON Pointer subtree of a still-pending raw Vix inference request.',inputSchema:z.object({connection_id:uuid,request_id:uuid,pointer:z.string().min(1).regex(/^\//).default('/')}).strict(),outputSchema:z.object({connection_id:uuid,request_id:uuid,pointer:z.string(),value:z.unknown()}).strict(),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{'openai/toolInvocation/invoking':'Reading Vix context','openai/toolInvocation/invoked':'Vix context ready'}}),async a=>toolResult(await runtime.inferenceContext(a)));
 server.registerTool('vix_close',descriptor({title:'Close Vix',description:'Stop one active stock Vix connector process and its isolated transport.',inputSchema:z.object({connection_id:uuid}).strict(),outputSchema:z.object({status:z.enum(['closed','not_found']),connection_id:uuid}).strict(),annotations:{readOnlyHint:false,destructiveHint:false,openWorldHint:false,idempotentHint:true},_meta:{'openai/toolInvocation/invoking':'Closing Vix','openai/toolInvocation/invoked':'Vix closed'}}),async({connection_id})=>toolResult(await runtime.closeConnection(connection_id)));
 server.registerTool('github_capabilities',descriptor({title:'Check canonical GitHub authority',description:'Read the single active gh identity and scopes. This never refreshes credentials or starts device flow.',inputSchema:z.object({required_scopes:z.array(z.string().min(1)).default([])}).strict(),outputSchema:openRecord,annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:true,idempotentHint:true}}),async a=>toolResult(await runtime.githubCapabilities(a)));
 server.registerTool('github_issue_label',descriptor({title:'Apply reversible GitHub issue label',description:'Preflight the canonical GitHub identity and repo scope, then add or remove exactly one issue label. No credential fallback or interactive refresh is allowed.',inputSchema:z.object({repo:z.string().min(1),issue_number:z.number().int().min(1),label:z.string().min(1),action:z.enum(['add','remove']).default('add')}).strict(),outputSchema:openRecord,annotations:{readOnlyHint:false,destructiveHint:true,openWorldHint:true,idempotentHint:false}}),async a=>toolResult(await runtime.githubIssueLabel(a)));
}
export const securitySchemes=SECURITY;
